# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Telescreen < Formula
  desc "A screen for monitoring your daily job, in your terminal."
  homepage "https://github.com/maxgio92/telescreen"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maxgio92/telescreen/releases/download/v0.1.1/telescreen_0.1.1_darwin_amd64.tar.gz"
      sha256 "559538ef8cc7bc83606c46ab69442a6344ccc822cd0c2b0818bd5740ea3501f6"

      define_method(:install) do
        bin.install "telescreen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maxgio92/telescreen/releases/download/v0.1.1/telescreen_0.1.1_darwin_arm64.tar.gz"
      sha256 "f7cad1197b8e76f1faf27d057eee5dc4be8ff62fef9e0f264f3a3612fe1ddc17"

      define_method(:install) do
        bin.install "telescreen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxgio92/telescreen/releases/download/v0.1.1/telescreen_0.1.1_linux_amd64.tar.gz"
      sha256 "408f5dd5466f259a0388f675688a4399cbc81fabb9964eb403e764446ae5c21e"
      define_method(:install) do
        bin.install "telescreen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxgio92/telescreen/releases/download/v0.1.1/telescreen_0.1.1_linux_arm64.tar.gz"
      sha256 "0438bb1bbee9d663e2152ce5af01b27f4e28c5fcf801b22efd5504048e6a8728"
      define_method(:install) do
        bin.install "telescreen"
      end
    end
  end

  test do
    system "#{bin}/telescreen", "version"
  end
end
